# Generated by Django 5.0.6 on 2024-06-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
    ]
