# Generated by Django 5.0.6 on 2024-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='experience',
            field=models.IntegerField(max_length=20),
        ),
    ]
