# Generated by Django 5.0.6 on 2024-06-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_coding_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coding',
            name='image',
        ),
    ]
